#!/usr/bin/env python3
from pathlib import Path

import tiktoken
import yaml

TOKENIZER = "o200k_base"
SKILLS_ROOT = Path("plugins")
REPORT_PATH = Path("SKILL_TOKEN_REPORT.md")


def parse_frontmatter(text: str, path: Path) -> dict:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: missing YAML front matter")

    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            metadata = yaml.safe_load("\n".join(lines[1:index])) or {}
            if not isinstance(metadata, dict):
                raise ValueError(f"{path}: front matter must be a mapping")
            return metadata

    raise ValueError(f"{path}: unterminated YAML front matter")


def count_tokens(encoding, value: str) -> int:
    return len(encoding.encode(value))


def main() -> None:
    encoding = tiktoken.get_encoding(TOKENIZER)
    rows = []

    for path in sorted(SKILLS_ROOT.rglob("SKILL.md")):
        text = path.read_text(encoding="utf-8")
        metadata = parse_frontmatter(text, path)

        name = metadata.get("name") or path.parent.name
        description = metadata.get("description")
        if not isinstance(name, str) or not name.strip():
            raise ValueError(f"{path}: name must be a non-empty string")
        if not isinstance(description, str) or not description.strip():
            raise ValueError(f"{path}: description must be a non-empty string")

        rows.append(
            {
                "name": name,
                "path": path.as_posix(),
                "skill_tokens": count_tokens(encoding, text),
                "description_tokens": count_tokens(encoding, description),
            }
        )

    if not rows:
        raise ValueError("no SKILL.md files found under plugins/")

    total_skill_tokens = sum(row["skill_tokens"] for row in rows)
    total_description_tokens = sum(row["description_tokens"] for row in rows)

    report = [
        "# Skill Token Report",
        "",
        f"Generated by `scripts/skill_token_stats.py` using the `{TOKENIZER}` tokenizer.",
        "",
        "`SKILL.md tokens` counts the whole file. `description tokens` counts only the YAML front matter `description` value and is already included in the whole-file count.",
        "",
        "| Skill | SKILL.md tokens | description tokens | File |",
        "| --- | ---: | ---: | --- |",
    ]

    for row in rows:
        report.append(
            f"| `{row['name']}` | {row['skill_tokens']} | {row['description_tokens']} | `{row['path']}` |"
        )

    report.extend(
        [
            f"| **Total** | **{total_skill_tokens}** | **{total_description_tokens}** | |",
            "",
        ]
    )

    REPORT_PATH.write_text("\n".join(report), encoding="utf-8")


if __name__ == "__main__":
    main()
